name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Set up Go env
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
      - name: Run build script
        run: ./scripts/crossBuild.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/*.zip
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download build files artifacts 
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: build/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: playlist-dl CLI ${{ github.ref_name }}
          files: build/*.zip
